{
    'name': 'CPCM Pharma ERP',
    'version': '1.0',
    'category': 'Pharma',
    'summary': 'ERP pour la gestion de la prospection et distribution de médicaments - CPCM PHARMA',
    'author': 'AMIRAT Dehbia',
    'depends': ['base', 'sale', 'stock', 'crm', 'calendrier_jours_feries', 'mail'],
    'data': [
        #'security/security.xml',
        'security/ir.model.access.csv',
        #'data/cpcm.wilaya.csv',
        #'data/cpcm.commune.csv',
        #'views/cpcm_prospect_view.xml',
        'views/visite_views.xml',
        'views/commande_views.xml',
        #'report/report.xml',
        #'report/report_bon_commande_document.xml',
        #'data/email_template_commande.xml',
        'views/tournee_views.xml',
        #'views/stock_views.xml',
        'views/menu.xml',
        #'data/jours_data.xml',
        #'views/commande_dashboard_views.xml',
        #'views/confirmation_wizard_views.xml'

    ],
    #'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
}
